CREATE TABLE [dbo].[Agencies]
(
	[Id] INT NOT NULL IDENTITY,
    [BusinessId] INT  NOT NULL, 
    [IsActive] BIT NOT NULL, 
    [CreateDate] DATETIME NULL, 
    [ModifyDate] DATETIME NULL, 
    [CreateBy] NVARCHAR(50) NULL, 
    [ModifyBy] NVARCHAR(50) NULL, 
    [Name] NVARCHAR(256) NOT NULL, 
    [Type] NVARCHAR(256) NOT NULL, 
    [ContactName] NVARCHAR(256) NULL, 
    [PhoneNumber1] NVARCHAR(20) NOT NULL, 
    [PhoneNumber2] NVARCHAR(20) NULL, 
    [Email] NVARCHAR(256) NOT NULL, 
    [AddressLine1] NVARCHAR(256) NULL, 
    [AddressLine2] NVARCHAR(256) NULL, 
    [City] NVARCHAR(50) NULL, 
    [State] NVARCHAR(50) NULL, 
    [Country] NVARCHAR(50) NULL, 
    [Pincode] NVARCHAR(10) NULL, 
    CONSTRAINT [PK_Agencies] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Agencies_ToBusinesses_BusinessId] FOREIGN KEY ([BusinessId]) REFERENCES [Businesses]([Id]), 
)
