CREATE TABLE [dbo].[Businesses]
(
	[Id] INT NOT NULL  IDENTITY,
    [IsActive] BIT NOT NULL, 
    [CreateDate] DATETIME NOT NULL, 
    [CreateBy] NVARCHAR(256) NOT NULL, 
    [ModifyDate] DATETIME NULL, 
    [ModifyBy] NVARCHAR(256) NULL, 
    [Name] NVARCHAR(256) NOT NULL, 
    [Description] NVARCHAR(512) NULL, 
    [IsSelected] BIT NOT NULL, 
    [Image] NVARCHAR(256) NULL, 
    [GSTNumber] NVARCHAR(256) NULL, 
    [PhoneNumber] NVARCHAR(20) NULL, 
    [Email] NVARCHAR(256) NULL, 
    [AddressLine1] NVARCHAR(256) NULL, 
    [AddressLine2] NVARCHAR(256) NULL, 
    [City] NVARCHAR(50) NULL, 
    [StateId] INT NULL, 
    [CountryId] INT NULL, 
    [Pincode] NVARCHAR(10) NULL, 
    CONSTRAINT [PK_Businesses] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Businesses_ToStateMaster_StateId] FOREIGN KEY ([StateId]) REFERENCES [StateMaster]([Id]), 
    CONSTRAINT [FK_Businesses_ToCountryMaster_StateId] FOREIGN KEY ([CountryId]) REFERENCES [CountryMaster]([Id]), 
)
