CREATE TABLE [dbo].[Clients]
(
	[Id] INT NOT NULL IDENTITY,
    [BusinessId] INT  NOT NULL, 
    [IsActive] BIT NOT NULL, 
    [CreateDate] DATETIME NULL, 
    [ModifyDate] DATETIME NULL, 
    [CreateBy] NVARCHAR(50) NULL, 
    [ModifyBy] NVARCHAR(50) NULL, 
    [Name] NVARCHAR(256) NOT NULL, 
    [PhoneNumber1] NVARCHAR(20) NOT NULL, 
    [PhoneNumber2] NVARCHAR(20) NULL, 
    [Email] NVARCHAR(256) NOT NULL, 
    [AddressLine1] NVARCHAR(256) NULL, 
    [AddressLine2] NVARCHAR(256) NULL, 
    [City] NVARCHAR(50) NULL, 
    [StateId] INT NULL, 
    [CountryId] INT NULL, 
    [Pincode] NVARCHAR(10) NULL, 
    CONSTRAINT [PK_Clients] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Clients_ToBusinesses_BusinessId] FOREIGN KEY ([BusinessId]) REFERENCES [Businesses]([Id]), 
    CONSTRAINT [FK_Clients_ToStateMaster_StateId] FOREIGN KEY ([StateId]) REFERENCES [StateMaster]([Id]), 
    CONSTRAINT [FK_Clients_ToCountryMaster_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [CountryMaster]([Id]), 
)
